import { createSlice } from '@reduxjs/toolkit'

const initialState = {
  gender: [],
  visitType: [],
  paymentMethod: [],
  roles: [],
  branches: [],
  referralTypes: [],
  states: [],
  visitsType: [],
  packagesChosen: [],
  billTypes: [],
  otPersonDesignation: [],
  expenseCategories: [],
  expenseSubCategories: [],
  embryologyList: [],
  patientTypeList: [],
  labTestGroupList: [],
  labTestSampleTypeList: [],
  inventoryTypeList: [],
  taxCategoryList: [],
  manufacturerList: [],
  departmentList: [],
  vendorList: [],
  suppliesList: [],
  bloodGroupList: [],
  consultantTypeList: [],
  otProcedureList: [],
}

export const dropdownSlice = createSlice({
  name: 'dropdowns',
  initialState,
  reducers: {
    setDropdown: (state, action) => {
      const {
        gender,
        visitType,
        paymentMethod,
        roles,
        branches,
        referralTypes,
        maritalStatus,
        visitTypes,
        packagesChosen,
        consultationTypes,
        treatmentTypes,
        states,
        billTypes,
        otPersonDesignation,
        expenseCategories,
        expenseSubCategories,
        embryologyList,
        patientTypeList,
        labTestGroupList,
        labTestSampleTypeList,
        inventoryTypeList,
        taxCategoryList,
        manufacturerList,
        departmentList,
        vendorList,
        suppliesList,
        bloodGroupList,
        consultantTypeList,
        otProcedureList,
      } = action.payload
      return {
        ...state,
        gender,
        visitType,
        paymentMethod,
        roles,
        branches,
        referralTypes,
        maritalStatus,
        visitTypes,
        packagesChosen,
        consultationTypes,
        treatmentTypes,
        states,
        billTypes,
        otPersonDesignation,
        expenseCategories,
        expenseSubCategories,
        embryologyList,
        patientTypeList,
        labTestGroupList,
        labTestSampleTypeList,
        inventoryTypeList,
        taxCategoryList,
        manufacturerList,
        departmentList,
        vendorList,
        suppliesList,
        bloodGroupList,
        consultantTypeList,
        otProcedureList,
      }
    },
  },
})

// Action creators are generated for each case reducer function
export const { setDropdown } = dropdownSlice.actions

const dropdownReducer = dropdownSlice.reducer
export { dropdownReducer }
